### PR TITLE
feat: change background color

### PR DESCRIPTION
**Pull request by csouchet**
I tried different designs.

### Background `#4a505a`
4a505a

### Background `secondary` color of `Spectre.css`
secondary

### Background `#7a7a8b`
7a7a8b

### Background `#eeeef2`
eeeef2

### Background `#f4f4f7`
f4f4f7

### Background `#f9f9fa`
f9f9fa

### Background `#f4f4f7` with the border of the divider `#7a7a8b` (The current)
f4f4f7 + divider 7a7a8b

### CODE REVIEW

**Comment by tbouffard** [comment]
My preference goes to something which is not too contrasted like `#eeeef2`, `#f4f4f7`, `#f9f9fa` or secondary color of Spectre.css.
But I would like we try to switch colors between the nav bar and the background to ensure people see it. The eye shouldn't be too attracted by this change.

**Comment by csouchet** [comment]
I did some other tests for the page rendering.

# Page 
## Background


# Navbar
## Background

## Title
### Size

### Color for current displayed diagram

### Color for not displayed diagram

**Comment by csouchet** [comment]
I did some other tests for the page rendering (the background of the page is `#f4f4f7`).

# Navbar title: Color for current displayed diagram

# Navbar title: Color for not displayed diagram

**Comment by csouchet** [comment]
With @tbouffard, we choose this final rendering:
image
image
image

**Review by tbouffard — APPROVED** [review]

**Pull request merged**
